version: '3.7'

services:
  db:
    build:
      context: .
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U postgres' ]
      interval: 10s
      start_period: 40s
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGTZ: ${TIME_ZONE:-Europe/Moscow}
    volumes:
      - db:/var/lib/postgresql/data:rw
      - ./caps:/home/caps
      - ./conf:/home/conf
      - ./settings:/home/settings
    ports:
      - '5434:5432'

volumes:
  db: { }